# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  host: localhost
  adapter: postgresql
  encoding:
  database: db
  pool: 5
  username: api
  password: apI
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: db
  pool: 5
  username: api
  password: apI
